### PR TITLE
chore(*): switch to go mod and bump golang version to 1.13.x

### PR DESCRIPTION
**Pull request by iawia002**
**What this PR does / why we need it**:

* switch go mod
  * `github.com/prometheus/client_golang` and `github.com/uber/jaeger-client-go` has been upgraded to the latest version due to the dependency issue 

**Which issue(s) this PR is related to** *(optional, link to 3rd issue(s))*:

Fixes #

Reference to #

**Special notes for your reviewer**:

/cc @your-reviewer

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by kdada** [comment]
LGTM.

Would you make the same changes to `nirvana init`?

**Comment by iawia002** [comment]
> LGTM.
> 
> Would you make the same changes to `nirvana init`?

I will do it in a separate PR

**Comment by iawia002** [comment]
> LGTM.
> 
> Would you make the same changes to `nirvana init`?

I have synced go mod related changes to project init template in commit a53dee8
PTAL @kdada

**Comment by hezhizhen** [comment]
LGTM

**Pull request merged**
