### PR TITLE
fix(openapi): use existing spec path to avoid overwrite path

### PR DESCRIPTION
**Pull request by ddysher**
**What this PR does / why we need it**:

If existing spec path is found, do not init a new one.

Found the bug when writing readme; If we define multiple methods for the same url, only the last one exists in final api spec, all others will be overwritten.

**Which issue(s) this PR fixes** *(optional, close the issue(s) when PR gets merged)*:

**Special notes for your reviewer**:

/cc @liubog2008 

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by ddysher** [comment]
@liubog2008 can you add more unit test in the package (also covers this bug)?

**Comment by liubog2008** [comment]
There is a fatal bug... I'll fix it today = =
This PR can't fix the real problem

**Comment by liubog2008** [comment]
see #137

**Comment by ddysher** [comment]
SGTM

/close

**Pull request closed without merging**
