### PR TITLE
chore(cli): remove cli

### PR DESCRIPTION
**Pull request by kdada**
**What this PR does / why we need it**:

- chore(cli): remove cli
We have implemented a new package named `config`. Package `cli` is useless now.

**Which issue(s) this PR fixes** *(optional, close the issue(s) when PR gets merged)*:

Fixes #

**Special notes for your reviewer**:

/assign @ddysher 
/assign @zoumo 
/kind cleanup

**Release note**:

```release-note
Remove cli
```

### CODE REVIEW

**Comment by Jimexist** [comment]
so that now people can directly use cobra cli (and/or other choices?)

**Comment by ddysher** [comment]
@yejiayu FYI https://github.com/caicloud/nirvana/pull/159

**Comment by kdada** [comment]
@Jimexist 
Package config covers a lot of scenarios. You can simply use it by:
```go
func main() {
	cmd := config.NewDefaultNirvanaCommand()
	cmd.EnablePlugin(
		&metrics.Option{},
		&profiling.Option{Contention: true},
	)
	if err := cmd.Execute(v1.Descriptor()); err != nil {
		log.Fatal(err)
	}
}
```
If you want to add more commands, you can extract `cobra.Command` from cmd via `cmd.Command()`.

**Pull request merged**
