### PR TITLE
[WIP] fix: file upload

### PR DESCRIPTION
**Pull request by qianlei90**
**What this PR does / why we need it**:

nirvana在从request中获取文件时，抛弃了multipart.FileHeader，这个PR将multipart.FileHeader补回来了。

**Which issue(s) this PR is related to** *(optional, link to 3rd issue(s))*:

Fixes #

Reference to #

**Special notes for your reviewer**:

/cc @hezhizhen @iawia002 @ddysher 

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by whalecold** [comment]
> /close

怎么 close 了

**Comment by qianlei90** [comment]
> 怎么 close 了

因为我看着代码改了一下，然后不知道怎么去验证改得对不对了... 😓

**Pull request closed without merging**
