### PR TITLE
chore(travis): upgrade go version to latest

### LINKED ISSUE #202: Upgrade golang to v1.10
There are two versions we used: `v1.8` and `v1.9`. The latest version is `v1.10`.
There are some conflicts between `v1.10` and before versions (#172). In the lifecycle of release 0.2, we need upgrade golang verison to `v1.10`

### PR DESCRIPTION
**Pull request by kdada**
**What this PR does / why we need it**:

Upgrade go version from `1.8` and `1.9` to `1.10.x`.

**Which issue(s) this PR fixes** *(optional, close the issue(s) when PR gets merged)*:

Fixes #202 

**Special notes for your reviewer**:

/cc @ddysher 

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by ddysher** [comment]
from 1.8 & 1.9 -> 1.9 & 1.10, but .travis only has 1.10 in this PR?
> Upgrade go version from 1.8 and 1.9 to 1.9 and 1.10.

**Comment by kdada** [comment]
@ddysher 

> Upgrade go version from 1.8 and 1.9 to 1.10.x.

I have changed it.

**Comment by ddysher** [comment]
So this requires all projects using latest golang, is it too restrict?

**Comment by kdada** [comment]
No. This version is only used to build and test Nirvana. Users can still build their projects with golang 1.8 and later.

**Pull request merged**
