### PR TITLE
fix(openapi): correct api generation for map

### PR DESCRIPTION
**Pull request by kdada**
**What this PR does / why we need it**:

`nirvana api` did not generate schema for map type. This pr fixed it.

**Which issue(s) this PR is related to** *(optional, link to 3rd issue(s))*:

Fixes #

Reference to #

**Special notes for your reviewer**:

/cc @ddysher 
/cc @zjj2wry 

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by kdada** [comment]
This PR should be merged after #231

**Comment by ddysher** [comment]
@kdada any updates?

**Comment by kdada** [comment]
PTAL
@ddysher 
@zjj2wry

**Pull request merged**
