### PR TITLE
fix(#275): support encoded URI in request path

### LINKED ISSUE #275: Support encoded URI in request path
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:

**What you expected to happen**:

Support encoded URI in request path, like `/projects/caicloud%2Fnirvana`.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

### PR DESCRIPTION
**Pull request by supereagle**
**What this PR does / why we need it**:

Use `EscapedPath()` instead of `Path` to support encoded URI in request path.

**Which issue(s) this PR is related to** *(optional, link to 3rd issue(s))*:

Fixes #275

Reference to #

**Special notes for your reviewer**:

/cc @kdada 

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by supereagle** [comment]
@kdada  PTAL

**Comment by kdada** [comment]
Keep URI encoded can pass special chars to API handlers.  Why decode it?

**Comment by supereagle** [comment]
Now encoded URI like `/projects/caicloud%2Fnirvana` is not supported.

**Comment by supereagle** [comment]
> Keep URI encoded can pass special chars to API handlers. Why decode it?

For request with path `/projects/caicloud%2Fnirvana`, `req.URL.Path` is `/projects/caicloud%2Fnirvana`, and `req.URL.EscapedPath()` is `/projects/caicloud%2Fnirvana`.

**Comment by kdada** [comment]
I am not sure if this change will break something. But I'll merge it for this case.

/lgtm

**Pull request merged**
