### PR TITLE
feat(lint): add more linters

### PR DESCRIPTION
**Pull request by Jimexist**
**What this PR does**
add more linters

**why we need it**
cover more lint cases

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by ddysher** [comment]
Please use our commit style
> add more linters

Please remove such commits
> Merge branch 'master' into add-linter

What's the criteria for adding a new linter?

**Comment by Jimexist** [comment]
@ddysher can we ignore the specific commit messages, if we *enforce squash commits* for pull requests? So that:

- for individual comments before merging, we can revert or cherry-pick one (per comment)
- we can better identify bugs introduced by merging from `master` if they are causing passing builds to start to fail in a PR

**Comment by Jimexist** [comment]
criteria for adding linters:

- they make sense and are commonly supported
- until they introduced too much overheads in future development (e.g. enforcing a specific comment tag on EVERY function and struct).

**Comment by supereagle** [comment]
@Jimexist   Please fork this repo and create the PR from your forked repo.

**Comment by ddysher** [comment]
Good catch!  @supereagle 
> @Jimexist Please fork this repo and create the PR from your forked repo.

**Comment by ddysher** [comment]
@Jimexist Since there is already conflict, can we close the PR and then create a new PR from your own fork?

**Pull request closed without merging**
