### PR TITLE
feat(config): add PreConfigure and PostConfigure hooks

### PR DESCRIPTION
**Pull request by kdada**
**What this PR does / why we need it**:

Add PreConfigure and PostConfigure hooks.
After creating nirvana server, config becomes immutable. So we need the two hooks.

**Which issue(s) this PR fixes** *(optional, close the issue(s) when PR gets merged)*:

Fixes #

**Special notes for your reviewer**:

/cc @caitong93 
/cc @zoumo 

**Release note**:

```release-note
Add PreConfigure and PostConfigure hooks
```

### CODE REVIEW

**Comment by ddysher** [comment]
what's the use case?

**Comment by kdada** [comment]
@ddysher 
Users want to install some middlewares or handlers into config. But once `nirvana.NewServer` is called, its config will be locked and can't be modified.

**Comment by caitong93** [comment]
This is complicated, for more flexibility maybe we should let user to write `Run` function rather than generated it.
```
type CommandContext interface {
   Configure() error
}
cmd.Command(func(cc CommandContext, server server.Server) error {
   if err := cc.Configure(); err != nil {
       return err
    }
    //  Bootstrap: connect database, etc.
    //  Start the server.
    //  Shutdown the server.
    ...
})

```

cc @kdada

**Comment by kdada** [comment]
There is not only a `Run` function and you can't configure after server is created. So the `NirvanaCommandHook` provides four check points to users.

**Pull request merged**
