### PR TITLE
apply prettier to docs

### PR DESCRIPTION
**Pull request by Jimexist**
**What this PR does / why we need it**:

Add your description

**Which issue(s) this PR fixes** *(optional, close the issue(s) when PR gets merged)*:

Fixes #

**Special notes for your reviewer**:

/cc @kdada 
/cc @zoumo 
/cc @walktall

**Release note**:

```release-note
apply prettier to docs
```

### CODE REVIEW

**Comment by ddysher** [comment]
@Jimexist can we hold the pr for a while?  i'm working on top level readme

**Comment by Jimexist** [comment]
you can close it, prefer to do it in one pass.

**Comment by Jimexist** [comment]
ideally it should be covered by using #147 pre-commit

**Comment by Jimexist** [comment]
ideally it should be covered by using #147 pre-commit

**Pull request closed without merging**
