### PR TITLE
refactor(analyzer): use packages.Load instead of build.Import to get better performance

### PR DESCRIPTION
**Pull request by iawia002**
**What this PR does / why we need it**:

There are basically two changes: first, use `packages.Load` instead of `build.Import` to analyze a package, and second, import all packages at once rather than individually.

Take storage-admin project as an example, API document generation:

<table>
<thead><tr><th>Before</th><th>After</th></tr></thead>
<tbody>

<tr><td>

```
1110.53s user
1321.23s system
499% cpu
8:06.60 total
```

</td>

<td>

```
144.90s user
23.57s system
610% cpu
27.607 total
```

</td></tr>
</tbody></table>

API client generation:

<table>
<thead><tr><th>Before</th><th>After</th></tr></thead>
<tbody>

<tr><td>

```
1070.64s user
1265.10s system
501% cpu
7:45.53 total
```

</td>

<td>

```
138.41s user
22.62s system
626% cpu
25.691 total
```

</td></tr>
</tbody></table>

The average time reduced from 8 minutes to half a minute.

**Which issue(s) this PR is related to** *(optional, link to 3rd issue(s))*:

Fixes #

Reference to #

**Special notes for your reviewer**:

/cc @your-reviewer

/kind feature

**Release note**:

```release-note
Use `packages.Load` instead of `build.Import` in API documentation/client generation to get better performance.
```

### CODE REVIEW

**Comment by xpofei** [comment]
release note 填一下吧 :yum:

**Comment by iawia002** [comment]
> release note 填一下吧 😋

Done

**Pull request merged**
