### PR TITLE
feat(middleware): implemented metrics middleware

### PR DESCRIPTION
**Pull request by lichuan0620**
**What this PR does / why we need it**:

Added metric middleware that mimick the functionality of the `metrics` plugin. Unlike a plugin, middleware can be added only to a subset of the descriptors.

**Which issue(s) this PR is related to** *(optional, link to 3rd issue(s))*:

Fixes #

Reference to #

**Special notes for your reviewer**:

/cc @supereagle @iawia002 

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by lichuan0620** [comment]
rebuild

**Comment by lichuan0620** [comment]
...how does this work? @iawia002

**Comment by supereagle** [comment]
> ...how does this work? @iawia002

Close and reopen this PR to re-trigger the CI.

**Pull request merged**
