### PR TITLE
chore(*): add flag dry-run

### PR DESCRIPTION
**Pull request by bbbmj**
**What this PR does / why we need it**:

Add your description

**Which issue(s) this PR is related to** *(optional, link to 3rd issue(s))*:

Fixes #

Reference to #

**Special notes for your reviewer**:

/cc @liubog2008 @kdada 

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by ddysher** [comment]
what happens if we do not have this option?

**Comment by bbbmj** [comment]
> what happens if we do not have this option?

Maybe the only thing we want to do is output swagger.json rather than serve ReDoc, 
another way is to use option `output` to prevent serve.

**Comment by kdada** [comment]
If you pass `--serve="" --output=./`, it will skip serving and just generate `swagger.json`. If the default behavior is not appropriate, you should focus on `--serve` rather than add a new flag.

**Comment by bbbmj** [comment]
> If you pass --serve="" --output=./, it will skip serving and just generate swagger.json. If the default behavior is not appropriate, you should focus on --serve rather than add a new flag.

Emmm....................LGTM

cc @ddysher @liubog2008 

/close

**Pull request closed without merging**
