### PR TITLE
feat(*): support operators in parameter helper

### PR DESCRIPTION
**Pull request by qianlei90**
**What this PR does / why we need it**:

Add your description

**Which issue(s) this PR is related to** *(optional, link to 3rd issue(s))*:

Fixes #

Reference to #

**Special notes for your reviewer**:

/cc @supereagle @iawia002 

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by iawia002** [comment]
I don't like this, the `BodyParameterFor` function provides a way to create a simple parameter, and if you need a more complex parameter, I think it's better to fill in the parameter you need manually. eg:

```go
{
	Source:      definition.Path/Body...,
	Name:        ...,
	Description: ...,
	Operators:   ...,
},
```

**Comment by qianlei90** [comment]
> I don't like this, the `BodyParameterFor` function provides a way to create a simple parameter, and if you need a more complex parameter, I think it's better to fill in the field you need manually. eg:
> 
> ```go
> {
> 	Source:      definition.Path/Body...,
> 	Name:        ...,
> 	Description: ...,
> 	Operators:   ...,
> }
> ```

- this PR is compatible
- it's really helpful and saved a lot of lines in my code.
- it makes code more clear

```golang
var createApp = definition.Definition{
	...
	Parameters: []definition.Parameter{
		definition.HeaderParameterFor(headerTenant, "tenant name"),
		definition.PathParameterFor("partition", "partition name"),
		definition.AutoParameterFor("app client", operator.ConversionToAppClient()),
		definition.BodyParameterFor("yaml content", operator.ConversionToApp()),
	},
	...
}
```

```golang
var createApp = definition.Definition{
	...
	Parameters: []definition.Parameter{
		definition.HeaderParameterFor(headerTenant, "tenant name"),
		definition.PathParameterFor("partition", "partition name"),
		{
			Source:      definition.Auto,
			Name:        "client",
			Description: "app client",
			Operators: []definition.Operator{
				operator.ConversionToAppClient(),
			},
		},
		{
			Source:      definition.Body,
			Name:        "yaml",
			Description: "yaml content",
			Operators: []definition.Operator{
				operator.ConversionToApp(),
			},
		,
	...
}
```

I think you can see the difference.

**Comment by iawia002** [comment]
I know it's compatible, the thing is `Operators` is not a required field, we don't have to make `BodyParameterFor` more complicated, and if you really like `BodyParameterFor("...", operator.ConversionToApp(), ...)` style, you can write your own util function in your repo.

**Pull request closed without merging**
