### PR TITLE
feat(#300): support tags for generated API docs

### LINKED ISSUE #300: Support tags for generated API docs
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:

**What you expected to happen**:

In OpenAPI specification, [tags](https://swagger.io/specification/#operationObject) can be used for logical grouping of operations by resources or any other qualifier.

Support tags for generated API docs.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
/assign

### PR DESCRIPTION
**Pull request by supereagle**
**What this PR does / why we need it**:

Add your description

**Which issue(s) this PR is related to** *(optional, link to 3rd issue(s))*:

Fixes #300

Reference to #

**Special notes for your reviewer**:

/cc @iawia002 @kdada 

**Release note**:

```release-note
feat(#300): support tags for generated API docs
```

### CODE REVIEW

**Comment by ddysher** [comment]
do we have tests for code path?

**Comment by supereagle** [comment]
> do we have tests for code path?

There is no tests for this.

**Comment by ddysher** [comment]
ok..

/approve

**Pull request merged**
